### ISSUE TITLE
SCSS issue with node_modules SCSS file

### ISSUE THREAD

**Issue by clayne11** [nathantreid/meteor-css-modules#32]
Cross-posting from Meteor issues - I'm starting to think this is a CSS modules bug since I don't have this issue with `fourseven:scss`.

https://github.com/meteor/meteor/issues/6950

**Comment by clayne11** [comment]
`nathanreid:css-modules` also doesn't support relative paths that don't start with `./`, like `@import "test.scss"` - it needs to be `@import "./test.scss"`. Both are perfectly valid in SCSS-land though.

**Comment by akanix42** [comment]
Sounds like a bug to me - that isn't a case I took into account. Should be easy enough to fix, though.

**Comment by helitack** [comment]
Sounds like two separate but similar issues here.
1. Should be able to exclude folders from eager loading through config and perhaps even exclude `/node_modules` by default.
2. Should support relative paths that don't start with `./`. Very common in big libs like bootstrapv4.

+1 on both of these.

**Comment by akanix42** [comment]
Sorry for the delay on this - both of these are fixed in 1.2.0. I've documented the new ignorePaths option here: https://github.com/nathantreid/meteor-css-modules/wiki/Package-Options

For react-select, the ignorePaths options is still required because there appears to some other special configuration required to process the scss files (and of course, you don't really want to process them anyway).

**Comment by clayne11** [comment]
Confirmed fixed. I'm closing this.
