### ISSUE TITLE
How to change the naming convention?

### ISSUE THREAD

**Issue by Spiralis** [nathantreid/meteor-css-modules#58]
My components are in a folder-structure as suggested by newer Meteor projects. This means that the classname for any UI component always ends up starting with: `_imports_ui_components_` (or `_imports_ui_layouts_` for my layout components).  

Is there anyway I can configure css-modules to not include this first part of the path in the generated class-names? Other than  myself manually augmenting the styles imported, which seems like a bad idea...

BTW: Since all my layouts are postfixed with `Layout` then collisions will not occur, even if I remove all class-name prefixes that matches imports/ui/(components|layouts).

**Comment by akanix42** [comment]
There is currently no support for this, although I'd like to add it. In the meantime, you can customize it by forking the package and editing the value of sanitisedPath in the generatedScopeName function on [postcss-plugins.js line 14](https://github.com/nathantreid/meteor-css-modules/blob/master/postcss-plugins.js#L14).

**Comment by akanix42** [comment]
Thanks again for the pull request! I renamed `namingConvention` to `cssClassNamingConvention` since I just now also added `jsClassNamingConvention` (for camelCase #45 and eventually other options). I renamed `trimNameParts` to `replacements` and modified your implementation to use regular expression replacements.
You can still use it like you the original implementation, to remove the specified text from the class name:

``` json
"cssModules": {
  "cssClassNamingConvention": {
    "replacements": [
      "_imports_ui_components_",
      "_imports_ui_layouts_"
    ]
  }
}
```

You can also get more fancy:

``` json
"cssModules": {
  "cssClassNamingConvention": {
    "replacements": [
      "_imports_ui_(components|layouts)_"
    ]
  }
}
```

And you can do advanced replacements, like replacing "_imports" with "cats" and all the underscores with hypens:

``` json
"cssModules": {
  "cssClassNamingConvention": {
    "replacements": [
      ["_imports", "cats"],
      ["_", "g", "-"]
    ]
  }
}
```

See the [package options wiki page](https://github.com/nathantreid/meteor-css-modules/wiki/Package-Options) for more details.

**Comment by Spiralis** [comment]
Excellent, @nathantreid ! :+1:
